# Autograd with tensors

In [1]:
import torch

In [2]:
# create tensor
w = torch.randn(4,5,requires_grad=True)

In [3]:
w

tensor([[-0.5259, -0.3015, -0.9987, -0.7345,  0.1963],
        [ 0.3745,  0.8104,  0.4180, -1.8994, -0.6733],
        [ 2.4295,  0.1600,  0.9832, -0.4276, -0.8929],
        [-1.6738, -1.2183,  0.7792,  0.0638, -0.0109]], requires_grad=True)

In [4]:
w.requires_grad_(False) # set gradients to false

tensor([[-0.5259, -0.3015, -0.9987, -0.7345,  0.1963],
        [ 0.3745,  0.8104,  0.4180, -1.8994, -0.6733],
        [ 2.4295,  0.1600,  0.9832, -0.4276, -0.8929],
        [-1.6738, -1.2183,  0.7792,  0.0638, -0.0109]])

In [5]:
w.requires_grad_(True) # set gradients to true

tensor([[-0.5259, -0.3015, -0.9987, -0.7345,  0.1963],
        [ 0.3745,  0.8104,  0.4180, -1.8994, -0.6733],
        [ 2.4295,  0.1600,  0.9832, -0.4276, -0.8929],
        [-1.6738, -1.2183,  0.7792,  0.0638, -0.0109]], requires_grad=True)

In [6]:
y = torch.exp(w)

In [7]:
y

tensor([[ 0.5910,  0.7397,  0.3683,  0.4797,  1.2169],
        [ 1.4542,  2.2488,  1.5190,  0.1497,  0.5100],
        [11.3527,  1.1735,  2.6731,  0.6521,  0.4095],
        [ 0.1875,  0.2957,  2.1798,  1.0658,  0.9892]], grad_fn=<ExpBackward0>)

In [8]:
'''
By printing the gradient function we can see that torch keeps track of all gradients
'''
print(y.grad_fn)

In [9]:
outp = y.mean()

In [10]:
print(w.grad)

None


In [11]:
# we can calulate the gradient of mean(y) with respect to w; note y = exp(w)
outp.backward()

In [12]:
# print gradients of 'w' w.r.t. 'outp'
print(w.grad)

tensor([[0.0296, 0.0370, 0.0184, 0.0240, 0.0608],
        [0.0727, 0.1124, 0.0759, 0.0075, 0.0255],
        [0.5676, 0.0587, 0.1337, 0.0326, 0.0205],
        [0.0094, 0.0148, 0.1090, 0.0533, 0.0495]])


In [13]:
# stop tracking
print(w.detach)

<built-in method detach of Tensor object at 0x7a317f4c1120>


In [14]:
print(outp.requires_grad)

True


In [15]:
# tracking cal also be stopped by using the variable inside the 'no_grad()' block
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

False


In [18]:
print(outp.requires_grad)

False
