In [58]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [59]:
import torch

### Indexing and slicing

In [60]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [61]:
x[1,1]

tensor(3)

In [62]:
# shape not retained
x[:,1]

tensor([1, 3, 5])

In [63]:
# shape retained
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [64]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### View and Reshape

In [65]:
# only shows the view and does not return alter the original tensor
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [68]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x_view = x.view(2, 5)
x_reshape = x.reshape(2, 5)

In [70]:
x_view

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [71]:
x_reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [72]:
x[0] = 999
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [73]:
x_view

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [74]:
x_reshape

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [75]:
x_view.shape

torch.Size([2, 5])

In [76]:
# pytorth will automatically infer the second dimension
x.view(2,-1)

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [77]:
# works the same way of reshape
x.reshape(-1, 5)

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

### Arithmetic

In [78]:
a = torch.tensor([1.,2.,3.])
b = torch.Tensor([4,5,6])     # 'Tensor' automatically casts to float

In [79]:
a

tensor([1., 2., 3.])

In [80]:
b

tensor([4., 5., 6.])

In [81]:
a + b

tensor([5., 7., 9.])

In [82]:
torch.add(a, b)

tensor([5., 7., 9.])

In [83]:
# equivalent to 'assign_add' in tensorflow
a.add_(b)
a

tensor([5., 7., 9.])

### Dot Products and Matrix Multiplication

In [84]:
a = torch.tensor([1.,2.,3.])

In [85]:
a * b

tensor([ 4., 10., 18.])

In [86]:
torch.dot(a, b)

tensor(32.)

In [100]:
c = torch.arange(6).reshape(2,3)
d = torch.arange(6, 12).reshape(3,2)

In [105]:
c

tensor([[0, 1, 2],
        [3, 4, 5]])

In [106]:
d

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [107]:
torch.mm(c, d)

tensor([[ 28,  31],
        [100, 112]])

In [108]:
# euclidean norm
x = torch.Tensor([2, 3, 4, 5])
x.norm()

tensor(7.3485)

In [109]:
# number of elements
c.numel()

6