In [17]:
import numpy as np
import pandas as pd
import torch

In [18]:
torch.__version__

'1.9.1+cpu'

In [19]:
arr = np.array(list(range(6)))

In [20]:
arr.dtype

dtype('int32')

In [21]:
type(arr)

numpy.ndarray

### Converting to a tensor

In [22]:
torch.from_numpy(arr)

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [23]:
torch.as_tensor(arr)

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [24]:
x = torch.as_tensor(arr)
x.dtype

torch.int32

In [25]:
x2d = np.random.rand(2, 2)
x2d

array([[0.32615514, 0.14428352],
       [0.25028259, 0.33979691]])

In [26]:
torch.from_numpy(x2d)

tensor([[0.3262, 0.1443],
        [0.2503, 0.3398]], dtype=torch.float64)

In [27]:
x2d_tensor = torch.from_numpy(x2d)

Note how if you change the original numpy array, the associated tensor also changes.

In [29]:
x2d[0][0] = 99
x2d

array([[99.        ,  0.14428352],
       [ 0.25028259,  0.33979691]])

In [30]:
x2d_tensor

tensor([[99.0000,  0.1443],
        [ 0.2503,  0.3398]], dtype=torch.float64)

### To avoid this use 'torch.tensor' instead

In [31]:
arr = np.random.rand(3,3)
arr

array([[0.25785228, 0.59902513, 0.42127665],
       [0.87914926, 0.7526591 , 0.85254977],
       [0.24338186, 0.31437408, 0.56519395]])

In [32]:
arr_tensor = torch.tensor(arr)
arr_tensor

tensor([[0.2579, 0.5990, 0.4213],
        [0.8791, 0.7527, 0.8525],
        [0.2434, 0.3144, 0.5652]], dtype=torch.float64)

In [ ]:
arr[0]