In [17]:
import numpy as np
import pandas as pd
import torch

In [18]:
torch.__version__

'1.9.1+cpu'

In [19]:
arr = np.array(list(range(6)))

In [20]:
arr.dtype

dtype('int32')

In [21]:
type(arr)

numpy.ndarray

### Converting to a tensor

In [22]:
torch.from_numpy(arr)

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [23]:
torch.as_tensor(arr)

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [24]:
x = torch.as_tensor(arr)
x.dtype

torch.int32

In [25]:
x2d = np.random.rand(2, 2)
x2d

array([[0.32615514, 0.14428352],
       [0.25028259, 0.33979691]])

In [26]:
torch.from_numpy(x2d)

tensor([[0.3262, 0.1443],
        [0.2503, 0.3398]], dtype=torch.float64)

In [27]:
x2d_tensor = torch.from_numpy(x2d)

### Note how if you change the original numpy array, the associated tensor also changes.

In [29]:
x2d[0][0] = 99
x2d

array([[99.        ,  0.14428352],
       [ 0.25028259,  0.33979691]])

In [30]:
x2d_tensor

tensor([[99.0000,  0.1443],
        [ 0.2503,  0.3398]], dtype=torch.float64)

### To avoid this use 'torch.tensor' instead

In [31]:
arr = np.random.rand(3,3)
arr

array([[0.25785228, 0.59902513, 0.42127665],
       [0.87914926, 0.7526591 , 0.85254977],
       [0.24338186, 0.31437408, 0.56519395]])

In [32]:
arr_tensor = torch.tensor(arr)
arr_tensor

tensor([[0.2579, 0.5990, 0.4213],
        [0.8791, 0.7527, 0.8525],
        [0.2434, 0.3144, 0.5652]], dtype=torch.float64)

In [33]:
arr[0][0] = 99
arr

array([[99.        ,  0.59902513,  0.42127665],
       [ 0.87914926,  0.7526591 ,  0.85254977],
       [ 0.24338186,  0.31437408,  0.56519395]])

In [34]:
arr_tensor

tensor([[0.2579, 0.5990, 0.4213],
        [0.8791, 0.7527, 0.8525],
        [0.2434, 0.3144, 0.5652]], dtype=torch.float64)

### 'torch.tensor' vs 'torch.Tensor'

In [35]:
int_arr = np.array([1,2,3])
int_arr

array([1, 2, 3])

In [36]:
# 'int' datatype retained
torch.tensor(int_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
# converted to float
torch.Tensor(int_arr)

tensor([1., 2., 3.])

In [38]:
torch.Tensor(int_arr).dtype

torch.float32

## Initializing tensors from scratch

In [39]:
torch.empty(4, 4)

tensor([[1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39, 9.7346e-39]])

In [40]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
torch.zeros(2, 2, dtype = torch.int8)

tensor([[0, 0],
        [0, 0]], dtype=torch.int8)

In [43]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [44]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

In [46]:
torch.linspace(0, 3, 6)

tensor([0.0000, 0.6000, 1.2000, 1.8000, 2.4000, 3.0000])

In [47]:
torch.linspace(0, 3, 6).reshape(3, 2)

tensor([[0.0000, 0.6000],
        [1.2000, 1.8000],
        [2.4000, 3.0000]])

In [48]:
arr_tensor

tensor([[0.2579, 0.5990, 0.4213],
        [0.8791, 0.7527, 0.8525],
        [0.2434, 0.3144, 0.5652]], dtype=torch.float64)

In [51]:
arr_tensor = arr_tensor.type(torch.float32)

In [53]:
arr_tensor.dtype

torch.float32

## Random Initialization

In [54]:
# uniform
torch.rand(3, 3)

tensor([[0.0072, 0.1742, 0.4127],
        [0.7778, 0.9319, 0.6332],
        [0.1942, 0.2195, 0.1146]])

In [55]:
# standard normal
torch.randn(3, 3)

tensor([[-0.4248,  0.7113,  0.6898],
        [ 1.8814, -0.0493,  0.3274],
        [-0.9385,  0.0315, -0.1337]])